"""initial schema

Revision ID: 517fb9ea9e98
Revises: 
Create Date: 2026-03-02 02:59:23.989026
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '517fb9ea9e98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clinical_findings',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('snomed_id', sa.Text(), nullable=True),
    sa.Column('snomed_desc', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('finding_type', sa.Enum('symptom', 'sign', 'lab_value', 'vital_sign', 'imaging_finding', 'procedure_result', 'history_item', 'medication', 'demographic', name='finding_type'), nullable=False),
    sa.Column('normal_range', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_index('idx_cf_snomed', 'clinical_findings', ['snomed_id'], unique=False)
    op.create_index('idx_cf_type', 'clinical_findings', ['finding_type'], unique=False)
    op.create_table('diagnoses',
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('icd10_code', sa.Text(), nullable=True),
    sa.Column('icd10_desc', sa.Text(), nullable=True),
    sa.Column('snomed_id', sa.Text(), nullable=True),
    sa.Column('snomed_desc', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('acuity', sa.Enum('acute', 'chronic', 'acute_on_chronic', 'unspecified', name='acuity'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('diagnosis_id'),
    sa.UniqueConstraint('icd10_code', 'snomed_id', name='uq_diagnoses_icd10_snomed')
    )
    op.create_index('idx_dx_category', 'diagnoses', ['category'], unique=False)
    op.create_index('idx_dx_icd10', 'diagnoses', ['icd10_code'], unique=False)
    op.create_index('idx_dx_snomed', 'diagnoses', ['snomed_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.Text(), nullable=False),
    sa.Column('method_name', sa.Text(), nullable=False),
    sa.Column('method_type', sa.Enum('llm_direct', 'rag', 'fine_tuned', 'ensemble', 'sparse_retrieval', 'dense_retrieval', 'hybrid_retrieval', name='method_type'), nullable=False),
    sa.Column('task', sa.Enum('diagnosis_accuracy', 'context_summarization', 'evidence_retrieval', 'imaging_indication', name='eval_task'), nullable=False),
    sa.Column('split', sa.Enum('train', 'val', 'test', name='split_type'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('llm_call_log',
    sa.Column('call_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_llm_hash', 'llm_call_log', ['input_hash'], unique=False)
    op.create_index('idx_llm_stage', 'llm_call_log', ['stage'], unique=False)
    op.create_table('longitudinal_patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('race_ethnicity', sa.Text(), nullable=True),
    sa.Column('insurance', sa.Text(), nullable=True),
    sa.Column('pcp_name', sa.Text(), nullable=True),
    sa.Column('num_encounters', sa.Integer(), nullable=False),
    sa.Column('primary_diagnoses', sa.Text(), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('generation_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('processing_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('started', 'completed', 'failed', 'skipped', name='processing_status'), nullable=False),
    sa.Column('records_in', sa.Integer(), nullable=True),
    sa.Column('records_out', sa.Integer(), nullable=True),
    sa.Column('records_error', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('source_decks',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('deck_name', sa.Text(), nullable=True),
    sa.Column('deck_type', sa.Enum('board_exam', 'fact', name='deck_type'), nullable=False),
    sa.Column('anki_db_version', sa.Text(), nullable=True),
    sa.Column('note_count', sa.Integer(), nullable=True),
    sa.Column('card_count', sa.Integer(), nullable=True),
    sa.Column('model_names', sa.Text(), nullable=True),
    sa.Column('deck_hierarchy', sa.Text(), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('deck_id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('terminology_codes',
    sa.Column('code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('display', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('code_id'),
    sa.UniqueConstraint('system', 'code', name='uq_terminology_system_code')
    )
    op.create_index('idx_term_system_code', 'terminology_codes', ['system', 'code'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('diagnosis_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.Enum('pathognomonic', 'highly_suggestive', 'commonly_seen', 'risk_factor', 'protective', 'rules_out', name='dx_finding_rel'), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['clinical_findings.finding_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'finding_id', 'relationship', name='uq_df_dx_finding_rel')
    )
    op.create_index('idx_df_diagnosis', 'diagnosis_findings', ['diagnosis_id'], unique=False)
    op.create_index('idx_df_finding', 'diagnosis_findings', ['finding_id'], unique=False)
    op.create_table('longitudinal_encounters',
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('encounter_date', sa.Text(), nullable=False),
    sa.Column('encounter_type', sa.Enum('outpatient', 'ed', 'inpatient', 'icu', 'follow_up', 'procedure', 'telehealth', name='encounter_type'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('attending_name', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('source_question_ids', sa.Text(), nullable=True),
    sa.Column('encounter_order', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('generation_method', sa.Enum('template', 'llm', 'hybrid', name='generation_method'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['longitudinal_patients.patient_id'], ),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    op.create_index('idx_le_date', 'longitudinal_encounters', ['encounter_date'], unique=False)
    op.create_index('idx_le_patient', 'longitudinal_encounters', ['patient_id'], unique=False)
    op.create_table('patient_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['longitudinal_patients.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('user_id', 'patient_id', name='uq_pa_user_patient')
    )
    op.create_index('idx_pa_patient', 'patient_assignments', ['patient_id'], unique=False)
    op.create_index('idx_pa_user', 'patient_assignments', ['user_id'], unique=False)
    op.create_table('raw_cards',
    sa.Column('raw_card_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('anki_note_id', sa.Integer(), nullable=False),
    sa.Column('anki_card_id', sa.Integer(), nullable=True),
    sa.Column('anki_model_name', sa.Text(), nullable=True),
    sa.Column('anki_deck_name', sa.Text(), nullable=True),
    sa.Column('anki_tags', sa.Text(), nullable=True),
    sa.Column('field_data', sa.Text(), nullable=False),
    sa.Column('field_data_text', sa.Text(), nullable=True),
    sa.Column('media_refs', sa.Text(), nullable=True),
    sa.Column('card_ordinal', sa.Integer(), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('card_type', sa.Enum('board_exam', 'fact', name='card_type'), nullable=True),
    sa.Column('card_format', sa.Text(), nullable=True),
    sa.Column('classification_method', sa.Enum('rule_based', 'llm', name='classification_method'), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['source_decks.deck_id'], ),
    sa.PrimaryKeyConstraint('raw_card_id'),
    sa.UniqueConstraint('deck_id', 'anki_note_id', 'card_ordinal', name='uq_raw_cards_deck_note_ord')
    )
    op.create_index('idx_raw_cards_anki_note', 'raw_cards', ['anki_note_id'], unique=False)
    op.create_index('idx_raw_cards_deck', 'raw_cards', ['deck_id'], unique=False)
    op.create_table('board_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('raw_card_id', sa.Integer(), nullable=False),
    sa.Column('source_qid', sa.Text(), nullable=True),
    sa.Column('question_format', sa.Enum('mcq_vignette', 'cloze_objective', 'cloze_clinical', 'basic_qa', name='question_format'), nullable=False),
    sa.Column('vignette_text', sa.Text(), nullable=True),
    sa.Column('vignette_html', sa.Text(), nullable=True),
    sa.Column('question_stem', sa.Text(), nullable=True),
    sa.Column('clinical_setting', sa.Text(), nullable=True),
    sa.Column('answer_choices', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('correct_explanation', sa.Text(), nullable=True),
    sa.Column('distractor_explanations', sa.Text(), nullable=True),
    sa.Column('cloze_raw', sa.Text(), nullable=True),
    sa.Column('cloze_answers', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('organ_system', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('step_level', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('tags_normalized', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('rule_based', 'llm', 'hybrid', name='extraction_method'), nullable=False),
    sa.Column('extraction_model', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_card_id'], ['raw_cards.raw_card_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('idx_bq_format', 'board_questions', ['question_format'], unique=False)
    op.create_index('idx_bq_step', 'board_questions', ['step_level'], unique=False)
    op.create_index('idx_bq_subject', 'board_questions', ['subject'], unique=False)
    op.create_index('idx_bq_system', 'board_questions', ['organ_system'], unique=False)
    op.create_table('fact_cards',
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('raw_card_id', sa.Integer(), nullable=False),
    sa.Column('fact_format', sa.Enum('cloze_fact', 'basic_fact', 'image_occlusion', name='fact_format'), nullable=False),
    sa.Column('fact_text', sa.Text(), nullable=False),
    sa.Column('fact_text_cloze', sa.Text(), nullable=True),
    sa.Column('fact_context', sa.Text(), nullable=True),
    sa.Column('fact_summary', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('organ_system', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('resource_refs', sa.Text(), nullable=True),
    sa.Column('tags_normalized', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('rule_based', 'llm', 'hybrid', name='extraction_method'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_card_id'], ['raw_cards.raw_card_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index('idx_fc_specialty', 'fact_cards', ['specialty'], unique=False)
    op.create_index('idx_fc_subject', 'fact_cards', ['subject'], unique=False)
    op.create_table('benchmark_ground_truth',
    sa.Column('gt_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Enum('diagnosis_accuracy', 'context_summarization', 'evidence_retrieval', 'imaging_indication', name='eval_task'), nullable=False),
    sa.Column('granularity', sa.Enum('question', 'patient', 'encounter', name='gt_granularity'), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=True),
    sa.Column('split', sa.Enum('train', 'val', 'test', name='split_type'), nullable=True),
    sa.Column('num_diagnoses', sa.Integer(), nullable=True),
    sa.Column('num_evidence', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(granularity = 'question' AND question_id IS NOT NULL) OR (granularity = 'patient' AND patient_id IS NOT NULL) OR (granularity = 'encounter' AND encounter_id IS NOT NULL)", name='ck_bgt_granularity_id'),
    sa.ForeignKeyConstraint(['encounter_id'], ['longitudinal_encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['longitudinal_patients.patient_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['board_questions.question_id'], ),
    sa.PrimaryKeyConstraint('gt_id')
    )
    op.create_index('idx_bgt_encounter', 'benchmark_ground_truth', ['encounter_id'], unique=False)
    op.create_index('idx_bgt_patient', 'benchmark_ground_truth', ['patient_id'], unique=False)
    op.create_index('idx_bgt_question', 'benchmark_ground_truth', ['question_id'], unique=False)
    op.create_index('idx_bgt_split', 'benchmark_ground_truth', ['split'], unique=False)
    op.create_index('idx_bgt_task', 'benchmark_ground_truth', ['task'], unique=False)
    op.create_table('ehr_sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Enum('demographics', 'chief_complaint', 'hpi', 'pmh', 'psh', 'medications', 'allergies', 'family_history', 'social_history', 'ros', 'vitals', 'physical_exam', 'labs', 'imaging', 'pathology', 'other_studies', 'assessment', 'plan', name='section_type'), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=False),
    sa.Column('section_order', sa.SmallInteger(), nullable=False),
    sa.Column('extraction_method', sa.Enum('rule_based', 'llm', 'hybrid', name='extraction_method'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['board_questions.question_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index('idx_ehr_question', 'ehr_sections', ['question_id'], unique=False)
    op.create_index('idx_ehr_type', 'ehr_sections', ['section_type'], unique=False)
    op.create_table('fact_diagnosis_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Enum('defines', 'differentiates', 'treatment', 'epidemiology', 'mechanism', name='fact_dx_relevance'), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['fact_cards.fact_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'diagnosis_id', name='uq_fdl_fact_dx')
    )
    op.create_table('fact_finding_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Enum('defines', 'explains', 'interpretation', 'normal_variant', name='fact_cf_relevance'), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact_cards.fact_id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['clinical_findings.finding_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'finding_id', name='uq_ffl_fact_finding')
    )
    op.create_table('question_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('correct', 'distractor', 'secondary', 'predisposing', name='dx_role'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('rule_based', 'llm', 'manual', name='data_source'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.diagnosis_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['board_questions.question_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'diagnosis_id', 'role', name='uq_qd_question_dx_role')
    )
    op.create_index('idx_qd_diagnosis', 'question_diagnoses', ['diagnosis_id'], unique=False)
    op.create_index('idx_qd_question', 'question_diagnoses', ['question_id'], unique=False)
    op.create_table('question_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('ehr_section', sa.Text(), nullable=True),
    sa.Column('relevance', sa.Enum('key', 'supporting', 'background', 'distractor', name='finding_relevance'), nullable=True),
    sa.Column('source', sa.Enum('rule_based', 'llm', 'manual', name='data_source'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['clinical_findings.finding_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['board_questions.question_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'finding_id', name='uq_qf_question_finding')
    )
    op.create_index('idx_qf_finding', 'question_findings', ['finding_id'], unique=False)
    op.create_index('idx_qf_question', 'question_findings', ['question_id'], unique=False)
    op.create_table('encounter_ehr_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.Text(), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=False),
    sa.Column('source_section_id', sa.Integer(), nullable=True),
    sa.Column('is_modified', sa.Integer(), nullable=False),
    sa.Column('section_order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['longitudinal_encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['source_section_id'], ['ehr_sections.section_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ees_encounter', 'encounter_ehr_sections', ['encounter_id'], unique=False)
    op.create_table('evaluation_predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('gt_id', sa.Integer(), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gt_id'], ['benchmark_ground_truth.gt_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.run_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_ep_gt', 'evaluation_predictions', ['gt_id'], unique=False)
    op.create_index('idx_ep_run', 'evaluation_predictions', ['run_id'], unique=False)
    op.create_table('imaging_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('gt_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('body_region', sa.Text(), nullable=False),
    sa.Column('clinical_indication', sa.Text(), nullable=False),
    sa.Column('ordering_provider', sa.Text(), nullable=True),
    sa.Column('order_priority', sa.Enum('routine', 'stat', 'urgent', name='order_priority'), nullable=True),
    sa.Column('order_datetime', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['longitudinal_encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['gt_id'], ['benchmark_ground_truth.gt_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('idx_io_encounter', 'imaging_orders', ['encounter_id'], unique=False)
    op.create_index('idx_io_gt', 'imaging_orders', ['gt_id'], unique=False)
    op.create_table('relevance_judgments',
    sa.Column('judgment_id', sa.Integer(), nullable=False),
    sa.Column('gt_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Text(), nullable=False),
    sa.Column('passage_source', sa.Enum('ehr_section', 'fact_card', 'encounter_section', name='passage_source'), nullable=False),
    sa.Column('relevance_grade', sa.SmallInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.CheckConstraint('relevance_grade BETWEEN 0 AND 3', name='ck_rj_grade_range'),
    sa.ForeignKeyConstraint(['gt_id'], ['benchmark_ground_truth.gt_id'], ),
    sa.PrimaryKeyConstraint('judgment_id')
    )
    op.create_index('idx_rj_gt', 'relevance_judgments', ['gt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rj_gt', table_name='relevance_judgments')
    op.drop_table('relevance_judgments')
    op.drop_index('idx_io_gt', table_name='imaging_orders')
    op.drop_index('idx_io_encounter', table_name='imaging_orders')
    op.drop_table('imaging_orders')
    op.drop_index('idx_ep_run', table_name='evaluation_predictions')
    op.drop_index('idx_ep_gt', table_name='evaluation_predictions')
    op.drop_table('evaluation_predictions')
    op.drop_index('idx_ees_encounter', table_name='encounter_ehr_sections')
    op.drop_table('encounter_ehr_sections')
    op.drop_index('idx_qf_question', table_name='question_findings')
    op.drop_index('idx_qf_finding', table_name='question_findings')
    op.drop_table('question_findings')
    op.drop_index('idx_qd_question', table_name='question_diagnoses')
    op.drop_index('idx_qd_diagnosis', table_name='question_diagnoses')
    op.drop_table('question_diagnoses')
    op.drop_table('fact_finding_links')
    op.drop_table('fact_diagnosis_links')
    op.drop_index('idx_ehr_type', table_name='ehr_sections')
    op.drop_index('idx_ehr_question', table_name='ehr_sections')
    op.drop_table('ehr_sections')
    op.drop_index('idx_bgt_task', table_name='benchmark_ground_truth')
    op.drop_index('idx_bgt_split', table_name='benchmark_ground_truth')
    op.drop_index('idx_bgt_question', table_name='benchmark_ground_truth')
    op.drop_index('idx_bgt_patient', table_name='benchmark_ground_truth')
    op.drop_index('idx_bgt_encounter', table_name='benchmark_ground_truth')
    op.drop_table('benchmark_ground_truth')
    op.drop_index('idx_fc_subject', table_name='fact_cards')
    op.drop_index('idx_fc_specialty', table_name='fact_cards')
    op.drop_table('fact_cards')
    op.drop_index('idx_bq_system', table_name='board_questions')
    op.drop_index('idx_bq_subject', table_name='board_questions')
    op.drop_index('idx_bq_step', table_name='board_questions')
    op.drop_index('idx_bq_format', table_name='board_questions')
    op.drop_table('board_questions')
    op.drop_index('idx_raw_cards_deck', table_name='raw_cards')
    op.drop_index('idx_raw_cards_anki_note', table_name='raw_cards')
    op.drop_table('raw_cards')
    op.drop_index('idx_pa_user', table_name='patient_assignments')
    op.drop_index('idx_pa_patient', table_name='patient_assignments')
    op.drop_table('patient_assignments')
    op.drop_index('idx_le_patient', table_name='longitudinal_encounters')
    op.drop_index('idx_le_date', table_name='longitudinal_encounters')
    op.drop_table('longitudinal_encounters')
    op.drop_index('idx_df_finding', table_name='diagnosis_findings')
    op.drop_index('idx_df_diagnosis', table_name='diagnosis_findings')
    op.drop_table('diagnosis_findings')
    op.drop_table('auth_tokens')
    op.drop_index('idx_term_system_code', table_name='terminology_codes')
    op.drop_table('terminology_codes')
    op.drop_table('source_decks')
    op.drop_table('processing_log')
    op.drop_table('longitudinal_patients')
    op.drop_index('idx_llm_stage', table_name='llm_call_log')
    op.drop_index('idx_llm_hash', table_name='llm_call_log')
    op.drop_table('llm_call_log')
    op.drop_table('evaluation_runs')
    op.drop_index('idx_dx_snomed', table_name='diagnoses')
    op.drop_index('idx_dx_icd10', table_name='diagnoses')
    op.drop_index('idx_dx_category', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index('idx_cf_type', table_name='clinical_findings')
    op.drop_index('idx_cf_snomed', table_name='clinical_findings')
    op.drop_table('clinical_findings')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
